/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as QuemSomosTransparenciaRouteImport } from './routes/quem-somos.transparencia'
import { Route as QuemSomosNossaHistoriaRouteImport } from './routes/quem-somos.nossa-historia'
import { Route as QuemSomosEquipeRouteImport } from './routes/quem-somos.equipe'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'

const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjetosRoute,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoticiasRoute,
} as any)
const QuemSomosTransparenciaRoute = QuemSomosTransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => QuemSomosRoute,
} as any)
const QuemSomosNossaHistoriaRoute = QuemSomosNossaHistoriaRouteImport.update({
  id: '/nossa-historia',
  path: '/nossa-historia',
  getParentRoute: () => QuemSomosRoute,
} as any)
const QuemSomosEquipeRoute = QuemSomosEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => QuemSomosRoute,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-somos': typeof QuemSomosRouteWithChildren
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
  '/quem-somos/transparencia': typeof QuemSomosTransparenciaRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quem-somos': typeof QuemSomosRouteWithChildren
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
  '/quem-somos/transparencia': typeof QuemSomosTransparenciaRoute
  '/noticias': typeof NoticiasIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-somos': typeof QuemSomosRouteWithChildren
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
  '/quem-somos/transparencia': typeof QuemSomosTransparenciaRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/noticias'
    | '/projetos'
    | '/quem-somos'
    | '/projetos/$slug'
    | '/quem-somos/equipe'
    | '/quem-somos/nossa-historia'
    | '/quem-somos/transparencia'
    | '/noticias/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quem-somos'
    | '/projetos/$slug'
    | '/quem-somos/equipe'
    | '/quem-somos/nossa-historia'
    | '/quem-somos/transparencia'
    | '/noticias'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/noticias'
    | '/projetos'
    | '/quem-somos'
    | '/projetos/$slug'
    | '/quem-somos/equipe'
    | '/quem-somos/nossa-historia'
    | '/quem-somos/transparencia'
    | '/noticias/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  ProjetosRoute: typeof ProjetosRouteWithChildren
  QuemSomosRoute: typeof QuemSomosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/quem-somos/transparencia': {
      id: '/quem-somos/transparencia'
      path: '/transparencia'
      fullPath: '/quem-somos/transparencia'
      preLoaderRoute: typeof QuemSomosTransparenciaRouteImport
      parentRoute: typeof QuemSomosRoute
    }
    '/quem-somos/nossa-historia': {
      id: '/quem-somos/nossa-historia'
      path: '/nossa-historia'
      fullPath: '/quem-somos/nossa-historia'
      preLoaderRoute: typeof QuemSomosNossaHistoriaRouteImport
      parentRoute: typeof QuemSomosRoute
    }
    '/quem-somos/equipe': {
      id: '/quem-somos/equipe'
      path: '/equipe'
      fullPath: '/quem-somos/equipe'
      preLoaderRoute: typeof QuemSomosEquipeRouteImport
      parentRoute: typeof QuemSomosRoute
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof ProjetosRoute
    }
  }
}

interface NoticiasRouteChildren {
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasIndexRoute: NoticiasIndexRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

interface ProjetosRouteChildren {
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

interface QuemSomosRouteChildren {
  QuemSomosEquipeRoute: typeof QuemSomosEquipeRoute
  QuemSomosNossaHistoriaRoute: typeof QuemSomosNossaHistoriaRoute
  QuemSomosTransparenciaRoute: typeof QuemSomosTransparenciaRoute
}

const QuemSomosRouteChildren: QuemSomosRouteChildren = {
  QuemSomosEquipeRoute: QuemSomosEquipeRoute,
  QuemSomosNossaHistoriaRoute: QuemSomosNossaHistoriaRoute,
  QuemSomosTransparenciaRoute: QuemSomosTransparenciaRoute,
}

const QuemSomosRouteWithChildren = QuemSomosRoute._addFileChildren(
  QuemSomosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  ProjetosRoute: ProjetosRouteWithChildren,
  QuemSomosRoute: QuemSomosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
